/**
 * This file was generated by the Jeddict
 */
package futuretechschool.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author Andreas N
 */
@Entity
public class Education {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String name;

    @OneToMany(cascade = CascadeType.PERSIST)
    private List<Student> student;

    @OneToMany(cascade = CascadeType.PERSIST)
    private List<Course> course;

    public Education() {
    }    
    

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Student> getStudent() {
        if (student == null) {
            student = new ArrayList<>();
        }
        return this.student;
    }

    public void setStudent(List<Student> student) {
        this.student = student;
    }

    public void addStudent(Student student) {
        getStudent().add(student);
    }

    public void removeStudent(Student student) {
        getStudent().remove(student);
    }

    public List<Course> getCourse() {
        if (course == null) {
            course = new ArrayList<>();
        }
        return this.course;
    }

    public void setCourse(List<Course> course) {
        this.course = course;
    }

    public void addCourse(Course course) {
        getCourse().add(course);
    }

    public void removeCourse(Course course) {
        getCourse().remove(course);
    }

}